### ISSUE TITLE
mini-svg-data-uri (esm issues)

### ISSUE THREAD

**Issue by sync** [tw-in-js/twind-forms#1]
It looks like the final bundle is still trying to import mini-svg-data-uri even if it looks like it should have been inlined into the package itself:

package.json
```
 "bundledDependencies": [
    "mini-svg-data-uri"
  ]
```

So in a pure esm workflow I can't use twind-forms because of it.

<img width="818" alt="Screen Shot 2021-02-14 at 9 22 33 am" src="https://user-images.githubusercontent.com/21725/107863192-42d7d680-6ea6-11eb-93c1-c26199bb9277.png">

Reproduction (working):

(make sure to use chrome (constructible stylesheets)  and if you use skypack it will work because skypack cdn will turn non esm dependencies into esm compatible dependencies)

https://esm.codes/#aW1wb3J0IHsgTGl0RWxlbWVudCwgaHRtbCB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L2xpdC1lbGVtZW50JwppbXBvcnQgeyBjcmVhdGUsIGNzc29tU2hlZXQgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKaW1wb3J0IHsgd2l0aEZvcm1zIH0gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvQHR3aW5kL2Zvcm1zJwoKY29uc3Qgc2hlZXQgPSBjc3NvbVNoZWV0KHsgdGFyZ2V0OiBuZXcgQ1NTU3R5bGVTaGVldCgpIH0pCgpjb25zdCB7IHR3IH0gPSBjcmVhdGUoeyBzaGVldCwgcHJlZmxpZ2h0OiB3aXRoRm9ybXMoKSB9KQoKY2xhc3MgVHdpbmRFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgY3JlYXRlUmVuZGVyUm9vdCgpIHsKICAgIGNvbnN0IHNoYWRvdyA9IHN1cGVyLmNyZWF0ZVJlbmRlclJvb3QoKQogICAgc2hhZG93LmFkb3B0ZWRTdHlsZVNoZWV0cyA9IFtzaGVldC50YXJnZXRdCiAgICByZXR1cm4gc2hhZG93CiAgfQoKICByZW5kZXIoKSB7CiAgICByZXR1cm4gaHRtbGAKICAgICAgPG1haW4gY2xhc3M9IiR7dHdgaC1zY3JlZW4gYmctcHVycGxlLTQwMCBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlcmB9Ij4KICAgICAgICA8aDEgY2xhc3M9IiR7dHdgZm9udC1ib2xkIHRleHQoY2VudGVyIDV4bCB3aGl0ZSBzbTpncmF5LTgwMCBtZDpwaW5rLTcwMClgfSI+CiAgICAgICAgICBUaGlzIGlzIFR3aW5kIQogICAgICAgIDwvaDE+CiAgICAgIDwvbWFpbj4KICAgIGAKICB9Cn0KCmN1c3RvbUVsZW1lbnRzLmRlZmluZSgndHdpbmQtZWxlbWVudCcsIFR3aW5kRWxlbWVudCk7Cgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9ICc8dHdpbmQtZWxlbWVudD48L3R3aW5kLWVsZW1lbnQ+Jwo=

Reproduction (not working):

(make sure to use chrome (constructible stylesheets)  and if you use unpack it will not work because unpkg will not turn non esm dependencies into esm compatible dependencies)

https://esm.codes/#aW1wb3J0IHsgTGl0RWxlbWVudCwgaHRtbCB9IGZyb20gJ2h0dHBzOi8vY2RuLnNreXBhY2suZGV2L2xpdC1lbGVtZW50JwppbXBvcnQgeyBjcmVhdGUsIGNzc29tU2hlZXQgfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCcKaW1wb3J0IHsgd2l0aEZvcm1zIH0gZnJvbSAnaHR0cHM6Ly91bnBrZy5jb20vQHR3aW5kL2Zvcm1zQDAuMS4zL2Zvcm1zLmpzJwoKY29uc3Qgc2hlZXQgPSBjc3NvbVNoZWV0KHsgdGFyZ2V0OiBuZXcgQ1NTU3R5bGVTaGVldCgpIH0pCgpjb25zdCB7IHR3IH0gPSBjcmVhdGUoeyBzaGVldCwgcHJlZmxpZ2h0OiB3aXRoRm9ybXMoKSB9KQoKY2xhc3MgVHdpbmRFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7CiAgY3JlYXRlUmVuZGVyUm9vdCgpIHsKICAgIGNvbnN0IHNoYWRvdyA9IHN1cGVyLmNyZWF0ZVJlbmRlclJvb3QoKQogICAgc2hhZG93LmFkb3B0ZWRTdHlsZVNoZWV0cyA9IFtzaGVldC50YXJnZXRdCiAgICByZXR1cm4gc2hhZG93CiAgfQoKICByZW5kZXIoKSB7CiAgICByZXR1cm4gaHRtbGAKICAgICAgPG1haW4gY2xhc3M9IiR7dHdgaC1zY3JlZW4gYmctcHVycGxlLTQwMCBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlcmB9Ij4KICAgICAgICA8aDEgY2xhc3M9IiR7dHdgZm9udC1ib2xkIHRleHQoY2VudGVyIDV4bCB3aGl0ZSBzbTpncmF5LTgwMCBtZDpwaW5rLTcwMClgfSI+CiAgICAgICAgICBUaGlzIGlzIFR3aW5kIQogICAgICAgIDwvaDE+CiAgICAgIDwvbWFpbj4KICAgIGAKICB9Cn0KCmN1c3RvbUVsZW1lbnRzLmRlZmluZSgndHdpbmQtZWxlbWVudCcsIFR3aW5kRWxlbWVudCk7Cgpkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9ICc8dHdpbmQtZWxlbWVudD48L3R3aW5kLWVsZW1lbnQ+Jwo=

You can see mini-svg-data-uri report here:
https://www.skypack.dev/view/mini-svg-data-uri

**Comment by sync** [comment]
I then tried to tweak the settings inside twind-forms package.json to have it inlined for all bundles but was unsuccessful

**Comment by sastan** [comment]
Thanks for the report. Non-esm packages cause a lot of headaches. I've used the code from tailwindlabs. I'm preparing a release without mini-svg-data-uri.

See f86c989

**Comment by sastan** [comment]
Fixed with v0.1.4. Please re-open if you still have issues.
